import { z } from "zod";

export const upsertProjectRequisitionFormSchema = z.object({
  costCentreDepartment: z.string().min(1),
  hodDirectorName: z.string().min(1),
  applicationDate: z.coerce.date(),
  clientName: z.string().min(1),
  billingName: z.string().min(1),
  addressWithPincode: z.string().min(1),
  pincode: z.string().regex(/^\d{6}$/, "Pincode must be 6 digits"),
  gstNumber: z.string().length(15, "GST Number must be 15 characters"),
  gstType: z.enum(["REGISTERED", "UNREGISTERED"]),
  contactName: z.string().min(1),
  contactNumber: z.string().regex(/^\d{10}$/, "Contact number must be 10 digits"),
  designation: z.string().min(1),
  department: z.string().min(1),
  panTanNumber: z.string().length(10, "PAN/TAN Number must be 10 characters"),
  email: z.string().email(),
  workOrderValue: z.string().min(1),
  workOrderDate: z.coerce.date(),
  agreementNumber: z.string().optional().or(z.literal("")),
  agreementDate: z.coerce.date().optional(),
  projectStartingDate: z.coerce.date(),
  projectDurationDays: z.coerce.number().int().positive(),
  projectCompletionDate: z.coerce.date(),
  workOrderNumber: z.string().min(1),
  newProjectNumber: z.string().min(1),
  amountOfWorkOrder: z.string().min(1),
  gstAmount: z.string().min(1),
  emdAmount: z.string().min(1),
  pgSdAmount: z.string().min(1),
  pgDate: z.coerce.date().optional(),
  pgExpiryDate: z.coerce.date().optional(),
  nameOfWork: z.string().min(1),
  locationDistrict: z.string().min(1),
  state: z.string().min(1),
  approvedProjectNumber: z.string().min(1),
  approvedBy: z.string().min(1)
});