-- AlterTable
ALTER TABLE "Project" ADD COLUMN "woAmount" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "woGstAmount" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "woTotalAmount" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "excessAmount" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "excessGstAmount" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "excessTotalAmount" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "bgAmount" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "bgIssueDate" TIMESTAMP(3);
ALTER TABLE "Project" ADD COLUMN "bgExpiryDate" TIMESTAMP(3);
ALTER TABLE "Project" ADD COLUMN "emdAmount" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "emdIssueDate" TIMESTAMP(3);
ALTER TABLE "Project" ADD COLUMN "emdExpiryDate" TIMESTAMP(3);
