ALTER TABLE "Asset"
ADD COLUMN "soldAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "soldRemark" TEXT;

ALTER TABLE "AssetMaintenance"
DROP COLUMN IF EXISTS "sellAmount",
DROP COLUMN IF EXISTS "soldTo";
