export const DPR_TASK_DATA: Record<string, string[]> = {
  "Project Management": [
    "Submission of Monthly Progress Report",
    "Submission of Quaterly Progress Report",
    "Submission of Extension of Time Limit Proposal",
    "Submission of Excess / Extra Proposal",
    "Other"
  ],
  "Inception Report & QAP": [
    "Kick-off Meeting with client & preliminary Project site visit",
    "Geometric Design of Existing Alignment",
    "Existing Road Inventory",
    "Existing Bridges, Culverts & Structures Inventory",
    "Submission of Draft Inception Report & QAP",
    "Comments from Concern approval authority & Its Compliance",
    "Submission of Final Inception Report & QAP",
    "Approval of Final Inception Report & QAP",
    "Other"
  ],
  "Feasibility Report": [
    "Geometric Design for various Alignment options",
    "Detailed Topographic Survey",
    "Submission of Traffic surveys Report (incl. Volume count, Axel load, TMC, O-D survey etc..)",
    "Submission of Black Spots audit report",
    "Submission of Draft Alignment Option Report & Presentation",
    "Submission of Final Alignment Report",
    "Approval of Final Alignment Report",
    "Collect & Testing of Various materials (Cement, Steel, Aggregates, Bitumen etc.) and Submission of Material Report",
    "Submission of NSV Report",
    "Condition survey for Existing CD works, Bridges & Structures",
    "Submission of Inventory & Condition Survey Report",
    "Subgrade Characteristics and Strength survey (soil sample testing)",
    "Submission of Pavement Structural Strength Survey (BBD / FWD) Report",
    "Submission of Geo Technical Investigation and sub soil Exploration Report",
    "Submission of Hydraulic and Hydrological Survey report",
    "Submission of Environment and Social Impact Assessment report",
    "Submission of Draft Pavement Design report (With Alternative Design Options)",
    "Submission of Rate Analysis",
    "Submission of Cost / Block Estimate",
    "Submission of Economic and financial analysis report",
    "Submission of Preliminary land acquisition Report",
    "Submission of Alignment/Strip plan and Alignment Drawing (TCS)",
    "Submission of Draft Feasibility Report",
    "Comments from Concern approval authority & Its Compliance",
    "Submission of Final Feasibility Report",
    "Other"
  ],
  "LA-I Report": [
    "Collection of Village Maps & Land revenue records",
    "Liasion for appointment of CALA & Publication of 3A Gazette Notification",
    "Preparation of Draft 3A Notifications",
    "Submission of Estimated Cost of Land Acquisition",
    "Submission of LA-I Report incl. Strip / LA Plan",
    "Comments from Concern approval authority & Its Compliance",
    "Submission of Final LA-I Report incl. Strip/LA Plan",
    "Other"
  ],
  "Utility-I Report": [
    "Identification of surface utilities",
    "Ground Penetrating Radar (GPR) Survey for sub-surface utilities",
    "Submission of identification letter to Utility owner",
    "Consultation with Utility agency & discussion on relocation cost",
    "Submission of Utility Shifting proposals to user agency",
    "Submission of Utility-I Report & Utility relocation plan",
    "Other"
  ],
  "Clearance-I Report": [
    "Initial consultation with Environment/Forest/Wildlife/CRZ authorities",
    "Collection of Reserved Forest survey numbers",
    "Details/cost of trees being felled from Forest Office",
    "Preparation of EIA Report",
    "Mapping of CRZ Boundary by authorised agency",
    "Submission of Clearance proposals",
    "Submission of Clearance-I Report",
    "Other"
  ],
  "Detailed Project Report (DPR)": [
    "Detailed Topography Survey on Approved Alignment",
    "Submission of DPR Main Report & Draft DPR",
    "Submission of Design Based Report (Road Design)",
    "Submission of Traffic Report",
    "Submission of NSV Report",
    "Submission of FWD Report",
    "Submission of Final Pavement Design report",
    "Submission of Economic and financial analysis report",
    "Submission of Black Spot Audit report",
    "Submission of Design Based Report (Structure Design)",
    "Submission of Inventory & Condition survey report",
    "Submission of Geo-technical and sub-soil explorations report",
    "Submission of Hydraulic & Hydrological Investigation report",
    "Submission of Material Report",
    "Submission of Environmental and Social Impact Assessment report",
    "Submission of Technical Specifications",
    "Submission of Rate Analysis",
    "Submission of Detailed Estimates",
    "Submission of Drawings (Road/Highway, Structure & Facilities)",
    "Submission of Drainage Design Report",
    "Submission of Drainage Plan",
    "Comments from approval authority on Draft DPR",
    "Submission of Final DPR",
    "Approval of Final DPR",
    "Other"
  ],
  "Bid documents and civil works contract agreement": [
    "Submission of Draft Civil work contract Agreement with technical schedule",
    "Submission of Draft Bid Documents (RFP / NIT)",
    "Approval of Civil work contract Agreement & Bid Documents",
    "Other"
  ],
  "LA-II Report": [
    "Liasion for Publication of 3A Gazette Notification",
    "Fixing of Boundary pillar for PROW marking",
    "Joint measurement survey with authority",
    "Valuation of existing properties",
    "Liasion for Publication of 3D Gazette Notification",
    "Submission of LA-II Report incl. Final Strip/LA Plan",
    "Other"
  ],
  "Utility-II Report": [
    "Joint site inspection with competent authority",
    "Submission of Utility Shifting Estimates",
    "Collection of NO upgradation certificate",
    "Approval of Utility Shifting Estimates",
    "Submission of Utility-II Report & Final Utility relocation plan",
    "Other"
  ],
  "Clearance-II Report": [
    "Liasion for Public Hearing (EC)",
    "Final environment clearance by authority",
    "Joint site inspection with DFO (Forest Clearance)",
    "Liasion for FRA certificate",
    "Stage I forest clearance approval",
    "Stage II forest clearance approval",
    "Joint site inspection for Wildlife clearance",
    "Stage I Wild clearance approval",
    "Stage II Wild clearance approval",
    "Site Visit by GCZMA/State Govt (CRZ)",
    "Presentation before committee (CRZ)",
    "Final CRZ clearance",
    "Final GAD Approval (Railway/Irrigation etc.)",
    "Submission of Final Clearance-II Report",
    "Other"
  ],
  "Land Award Report (LA-III Report)": [
    "Liasion for Award Declaration (3G)",
    "Submission of Land Award Report",
    "Other"
  ],
  "Land possession Report (LA-IV Report)": [
    "Liasion for Deposition of compensation amount by Govt to CALA",
    "Liasion for Amount Disbursement to Land owners",
    "Receipt of Land Possession Certificate 3(E)",
    "Submission of Land possession Report",
    "Other"
  ]
};
